exclude: ["README.md"]
timezone: Europe/Berlin
permalink: /:year/:month/:day/:title:output_ext

title: EventCally Docs
description:
  de: Dokumentation für EventCally
  en: Documentation for EventCally

url: https://docs.eventcally.com
baseurl:
parent_url: https://eventcally.com

languages: ["de", "en"]
default_lang: "de"
exclude_from_localization: ["assets", "favicon.ico", "CNAME"]
parallel_localization: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-category-pages
